
package publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "ExisteUnUsuarioYaRegistradoException", targetNamespace = "http://publicar/")
public class ExisteUnUsuarioYaRegistradoException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private ExisteUnUsuarioYaRegistradoException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public ExisteUnUsuarioYaRegistradoException_Exception(String message, ExisteUnUsuarioYaRegistradoException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public ExisteUnUsuarioYaRegistradoException_Exception(String message, ExisteUnUsuarioYaRegistradoException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.ExisteUnUsuarioYaRegistradoException
     */
    public ExisteUnUsuarioYaRegistradoException getFaultInfo() {
        return faultInfo;
    }

}
