
package publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoExistenOfertasSeleccionarPostulanteException", targetNamespace = "http://publicar/")
public class NoExistenOfertasSeleccionarPostulanteException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoExistenOfertasSeleccionarPostulanteException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoExistenOfertasSeleccionarPostulanteException_Exception(String message, NoExistenOfertasSeleccionarPostulanteException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoExistenOfertasSeleccionarPostulanteException_Exception(String message, NoExistenOfertasSeleccionarPostulanteException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.NoExistenOfertasSeleccionarPostulanteException
     */
    public NoExistenOfertasSeleccionarPostulanteException getFaultInfo() {
        return faultInfo;
    }

}
