
package publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "NoHayTiposException", targetNamespace = "http://publicar/")
public class NoHayTiposException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private NoHayTiposException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public NoHayTiposException_Exception(String message, NoHayTiposException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public NoHayTiposException_Exception(String message, NoHayTiposException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.NoHayTiposException
     */
    public NoHayTiposException getFaultInfo() {
        return faultInfo;
    }

}
