
package publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "OfertasLaboralesNoExistenNingunaException", targetNamespace = "http://publicar/")
public class OfertasLaboralesNoExistenNingunaException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private OfertasLaboralesNoExistenNingunaException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public OfertasLaboralesNoExistenNingunaException_Exception(String message, OfertasLaboralesNoExistenNingunaException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public OfertasLaboralesNoExistenNingunaException_Exception(String message, OfertasLaboralesNoExistenNingunaException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.OfertasLaboralesNoExistenNingunaException
     */
    public OfertasLaboralesNoExistenNingunaException getFaultInfo() {
        return faultInfo;
    }

}
