
package publicar;

import jakarta.xml.ws.WebFault;


/**
 * This class was generated by the XML-WS Tools.
 * XML-WS Tools 4.0.0
 * Generated source version: 3.0
 * 
 */
@WebFault(name = "UsuarioSinPostulacionesException", targetNamespace = "http://publicar/")
public class UsuarioSinPostulacionesException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private UsuarioSinPostulacionesException faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public UsuarioSinPostulacionesException_Exception(String message, UsuarioSinPostulacionesException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param cause
     * @param faultInfo
     * @param message
     */
    public UsuarioSinPostulacionesException_Exception(String message, UsuarioSinPostulacionesException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: publicar.UsuarioSinPostulacionesException
     */
    public UsuarioSinPostulacionesException getFaultInfo() {
        return faultInfo;
    }

}
